language: cpp
sudo: false

compiler: clang

matrix:
    include:
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - CONF=release
        - os: linux
          dist: bionic
          compiler: gcc
          env:
              - CONF=debug
              - EXTRA_CMAKE_FLAGS='-DENABLE_COVERAGE=ON'
          after_success:
              - pip install --user cpp-coveralls
              - $CXX --version
              - /usr/bin/gcov-9 --v
              - coveralls -h
              - coveralls -r .. --gcov /usr/bin/gcov-9 --gcov-options '\-lp' -i calc
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CONF=release
        - os: linux
          dist: bionic
          compiler: clang
          env:
              - CONF=debug


# Handle git submodules yourself
git:
    submodules: false

# Use sed to replace the SSH URL with the public URL, then initialize submodules
before_install:
    - sed -i 's/git@github.com:/https:\/\/github.com\//' .gitmodules
    - git submodule update --init --recursive


install:
  - if [ "$CXX" = "g++" ]; then export CXX="g++-9" CC="gcc-9"; fi


addons:
  apt:
    update: true
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - gcc-9
      - g++-9
      - lcov

script:
  - $CXX --version
  - mkdir build
  - cd build
  - cmake -DCMAKE_BUILD_TYPE=$CONF $EXTRA_CMAKE_FLAGS ..
  - cmake --build .
  - ./tests

